name: Build ReJSON DLL

on:
  workflow_dispatch:   # bisa dijalankan manual dari tab Actions
  push:                # jalan setiap ada commit baru
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
          override: true

      - name: Install mingw
        run: sudo apt-get update && sudo apt-get install -y mingw-w64

      - name: Build ReJSON (Windows DLL)
        run: cargo build --release --workspace --target x86_64-pc-windows-gnu

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: redis_json-dll
          path: target/x86_64-pc-windows-gnu/release/redis_json.dll
